### PR TITLE
improve controls (WIP)

### PR DESCRIPTION
**Pull request by McDiod**

### CODE REVIEW

**Comment by McDiod** [comment]
This brings:

* doubleclick to create WP
* leftclick anywhere to unselect group (+event)
* drag&drop waypoint
* delete waypoint with DEL key

Any more ideas to improve usability @nomisum ?

**Comment by nomisum** [comment]
Sounds great already. I will make a new issue if something comes to my mind.

**Comment by nomisum** [comment]
for me personally one or two custom waypoints would be useful, which i can fill with my own code if i need to. or something like "onWaypointComplete" for each waypoint type.

use case: i want to be able to move soldiers into barracks/towers for caching/despawn and/or add custom actions like shooting flares.

**Comment by nomisum** [comment]
I'm testing this PR now.

- Help Keybind seems glitchy (doesnt seem to work when opening high command a second time - looks awesome though)

I would further suggest:
- right click to set waypoint (double left click collides with deselection if not done properly)
- ability show all waypoints of all units at once
- floating menu with meta data of currently selected unit (unit state, type, speed, next waypoint infos)

**Comment by McDiod** [comment]
> right click to set waypoint

This might conflict with context menus. I could make it shift+rightclick to be consistent with 3den. I think it's less intuitive, but looking at the help menu once will solve that for the user.

Edit: did this

***

> ability show all waypoints of all units at once

Not sure where to put this. Doesn't really belong in either of the context menus.

Edit: Actually, functionality for selecting multiple groups at once wouldn't be too hard to implement. I think I will do that in a separate PR. Waypoints of selected groups are visible. Click + drag to select from map. Ctrl + A to select all.

***

> floating menu with meta data

You got an example for this, design wise? Don't know what exactly you have in mind.

**Comment by nomisum** [comment]
will give an example, give me some days time

**Comment by nomisum** [comment]
something like this: giving a brief overview over unit and waypoint properties

overlay

**Pull request merged**
